version: '3'

#secrets
secrets:
  credentials:
    file : ../secrets/credentials.txt
  db_password:
    file : ../secrets/db_password.txt
  db_root_password:
    file : ../secrets/db_root_password.txt

#network
networks:
  net :
    driver : bridge  

#volume
volumes:
  database_volume:
    driver_opts:
      device: /home/${USER}/data/database_volume
      o: bind
      type: none
  wordpress_volume:
    driver_opts:
      device: /home/${USER}/data/wordpress_volume
      o: bind
      type: none

#services

services:


  #database
  mariadb :
    image : mariadb:impermeable
    build :
      context: ./requirements/mariadb
    container_name : mariadb
    restart: always
    networks :
      - net
    volumes :
      - database_volume:/var/lib/mysql
    secrets :
      - credentials
      - db_password
      - db_root_password
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    ports :
      - "3306:3306"


  #wordpress
  wordpress :
    image : wordpress:impermeable
    build :
      context : ./requirements/wordpress
    container_name : wordpress
    restart: always
    networks :
      - net
    volumes :
      - wordpress_volume:/var/www/html/wordpress
    secrets :
      - credentials
      - db_password
      - db_root_password    
    environment :
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - WP_TITLE=${WP_TITLE}
    ports :
      - "9000:9000"
    depends_on :
      - mariadb


  #nginx
  nginx :
    image : nginx:impermeable
    build :
      context : ./requirements/nginx
    container_name : nginx
    restart: always
    networks :
      - net
    volumes :
      - wordpress_volume:/var/www/html/wordpress
    secrets :
      - credentials
      - db_password
      - db_root_password
    ports :
      - "443:443"
    depends_on :
      - wordpress
      - mariadb
    environment :
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}

#### BOONUS ####

#redis
  redis :
    image : redis:impermeable
    build :
      context : ./requirements/bonus/redis
    container_name : redis
    restart: always
    networks :
      - net
    ports :
      - "6379:6379"
    depends_on :
      - wordpress

#codvisor
  codvisor :
    image : codvisor:impermeable
    build :
      context : ./requirements/bonus/codvisor
    container_name : codvisor
    restart: always
    networks :
      - net
    ports :
      - "8080:8080"
    depends_on :
      - wordpress

#adminer
  adminer :
    image : adminer:impermeable
    build :
      context : ./requirements/bonus/adminer
    container_name : adminer
    restart: always
    networks :
      - net
    ports :
      - "9090:9090"
    depends_on :
      - mariadb

#static website
  staticWeb:
    image : staticweb:impermeable
    build :
      context : ./requirements/bonus/staticWeb
    container_name : staticWeb
    restart: always
    networks :
      - net
    ports :
      - "4242:4242"

# FTP Service
  ftp:
    image : staticweb:impermeable
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    networks:
      - net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    ports:
      - "21:21"
      - "30000-30100:30000-30100"
    secrets:
      - credentials
    depends_on:
      - wordpress